apiVersion: v1
kind: Service
metadata:
  name: {{ include "promptlab.fullname" . }}-api
  labels:
    {{- include "promptlab.labels" . | nindent 4 }}
    app.kubernetes.io/component: api
spec:
  type: ClusterIP
  selector:
    {{- include "promptlab.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: api
  ports:
    - port: {{ .Values.api.port }}
      targetPort: {{ .Values.api.port }}
      protocol: TCP
